project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Aaron Gullickson"
  navbar:
    left:
      - icon: sticky
        text: Blog Posts
        href: posts.qmd
      - icon: book
        text: "Statistics Analysis in Sociology"
        href: https://stat-analysis.netlify.app/
        target: _blank
      - icon: book
        text: "Practical Data Analysis Using R"
        href: https://practical-data-analysis-r.netlify.app/
        target: _blank
        
#  sidebar:
#    style: "floating"
#    search: true
#    contents:
      # - icon: sticky
      #   text: Blog Posts
      #   href: posts.qmd
      # - section: "Textbooks"
      #   contents:
      #   - icon: book
      #     text: "Statistics Analysis in Sociology"
      #     href: https://stat-analysis.netlify.app/
      #     target: _blank
      #   - icon: book
      #     text: "Practical Data Analysis Using R"
      #     href: https://practical-data-analysis-r.netlify.app/
      #     target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



