<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Confidence Intervals | Statistical Analysis in Sociology</title>
  <meta name="description" content="Textbook for Statistical Analysis for University of Oregon Sociology">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Confidence Intervals | Statistical Analysis in Sociology />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Textbook for Statistical Analysis for University of Oregon Sociology" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Confidence Intervals | Statistical Analysis in Sociology />
  
  <meta name="twitter:description" content="Textbook for Statistical Analysis for University of Oregon Sociology" />
  

<meta name="author" content="Aaron Gullickson">


<meta name="date" content="2019-03-15">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="the-concept-of-the-sampling-distribution.html">
<link rel="next" href="hypothesis-tests.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="understanding-data.html"><a href="understanding-data.html"><i class="fa fa-check"></i>Understanding Data</a><ul>
<li class="chapter" data-level="" data-path="what-does-data-look-like.html"><a href="what-does-data-look-like.html"><i class="fa fa-check"></i>What Does Data Look Like?</a><ul>
<li class="chapter" data-level="" data-path="what-does-data-look-like.html"><a href="what-does-data-look-like.html#the-observations"><i class="fa fa-check"></i>The observations</a></li>
<li class="chapter" data-level="" data-path="what-does-data-look-like.html"><a href="what-does-data-look-like.html#the-variables"><i class="fa fa-check"></i>The variables</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="what-can-we-do-with-data.html"><a href="what-can-we-do-with-data.html"><i class="fa fa-check"></i>What Can We Do With Data?</a><ul>
<li class="chapter" data-level="" data-path="what-can-we-do-with-data.html"><a href="what-can-we-do-with-data.html#how-is-a-variable-distributed"><i class="fa fa-check"></i>How is a variable distributed?</a></li>
<li class="chapter" data-level="" data-path="what-can-we-do-with-data.html"><a href="what-can-we-do-with-data.html#measuring-association"><i class="fa fa-check"></i>Measuring association</a></li>
<li class="chapter" data-level="" data-path="what-can-we-do-with-data.html"><a href="what-can-we-do-with-data.html#making-statistical-inferences"><i class="fa fa-check"></i>Making statistical inferences</a></li>
<li class="chapter" data-level="" data-path="what-can-we-do-with-data.html"><a href="what-can-we-do-with-data.html#building-models"><i class="fa fa-check"></i>Building Models</a></li>
<li class="chapter" data-level="" data-path="what-can-we-do-with-data.html"><a href="what-can-we-do-with-data.html#observational-data-experimental-thinking"><i class="fa fa-check"></i>Observational Data, Experimental Thinking</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-distribution-of-a-variable.html"><a href="the-distribution-of-a-variable.html"><i class="fa fa-check"></i>The Distribution of a Variable</a><ul>
<li class="chapter" data-level="" data-path="what-is-a-distribution.html"><a href="what-is-a-distribution.html"><i class="fa fa-check"></i>What is a Distribution?</a><ul>
<li class="chapter" data-level="" data-path="what-is-a-distribution.html"><a href="what-is-a-distribution.html#looking-at-the-distribution-of-a-categorical-variable"><i class="fa fa-check"></i>Looking at the distribution of a categorical variable</a></li>
<li class="chapter" data-level="" data-path="what-is-a-distribution.html"><a href="what-is-a-distribution.html#looking-at-the-distribution-of-a-quantitative-variable"><i class="fa fa-check"></i>Looking at the distribution of a quantitative variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="measuring-the-center-of-a-distribution.html"><a href="measuring-the-center-of-a-distribution.html"><i class="fa fa-check"></i>Measuring the Center of a Distribution</a><ul>
<li class="chapter" data-level="" data-path="measuring-the-center-of-a-distribution.html"><a href="measuring-the-center-of-a-distribution.html#the-mean"><i class="fa fa-check"></i>The mean</a></li>
<li class="chapter" data-level="" data-path="measuring-the-center-of-a-distribution.html"><a href="measuring-the-center-of-a-distribution.html#the-median"><i class="fa fa-check"></i>The median</a></li>
<li class="chapter" data-level="" data-path="measuring-the-center-of-a-distribution.html"><a href="measuring-the-center-of-a-distribution.html#the-mode"><i class="fa fa-check"></i>The mode</a></li>
<li class="chapter" data-level="" data-path="measuring-the-center-of-a-distribution.html"><a href="measuring-the-center-of-a-distribution.html#comparing-the-mean-and-median"><i class="fa fa-check"></i>Comparing the mean and median</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="percentiles-and-the-five-number-summary.html"><a href="percentiles-and-the-five-number-summary.html"><i class="fa fa-check"></i>Percentiles and the Five Number Summary</a><ul>
<li class="chapter" data-level="" data-path="percentiles-and-the-five-number-summary.html"><a href="percentiles-and-the-five-number-summary.html#percentiles"><i class="fa fa-check"></i>Percentiles</a></li>
<li class="chapter" data-level="" data-path="percentiles-and-the-five-number-summary.html"><a href="percentiles-and-the-five-number-summary.html#the-five-number-summary"><i class="fa fa-check"></i>The five number summary</a></li>
<li class="chapter" data-level="" data-path="percentiles-and-the-five-number-summary.html"><a href="percentiles-and-the-five-number-summary.html#boxplots"><i class="fa fa-check"></i>Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="measuring-the-spread-of-a-distribution.html"><a href="measuring-the-spread-of-a-distribution.html"><i class="fa fa-check"></i>Measuring the Spread of a Distribution</a><ul>
<li class="chapter" data-level="" data-path="measuring-the-spread-of-a-distribution.html"><a href="measuring-the-spread-of-a-distribution.html#range-and-interquartile-range"><i class="fa fa-check"></i>Range and interquartile range</a></li>
<li class="chapter" data-level="" data-path="measuring-the-spread-of-a-distribution.html"><a href="measuring-the-spread-of-a-distribution.html#variance-and-standard-deviation"><i class="fa fa-check"></i>Variance and standard deviation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="measuring-association-1.html"><a href="measuring-association-1.html"><i class="fa fa-check"></i>Measuring Association</a><ul>
<li class="chapter" data-level="" data-path="the-two-way-table.html"><a href="the-two-way-table.html"><i class="fa fa-check"></i>The Two-Way Table</a><ul>
<li class="chapter" data-level="" data-path="the-two-way-table.html"><a href="the-two-way-table.html#conditional-distributions"><i class="fa fa-check"></i>Conditional distributions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="odds-ratio-advanced.html"><a href="odds-ratio-advanced.html"><i class="fa fa-check"></i>Odds ratio (Advanced)</a></li>
<li class="chapter" data-level="" data-path="mean-differences.html"><a href="mean-differences.html"><i class="fa fa-check"></i>Mean Differences</a><ul>
<li class="chapter" data-level="" data-path="mean-differences.html"><a href="mean-differences.html#graphically-examining-differences-in-distributions"><i class="fa fa-check"></i>Graphically examining differences in distributions</a></li>
<li class="chapter" data-level="" data-path="mean-differences.html"><a href="mean-differences.html#comparing-differences-in-the-mean"><i class="fa fa-check"></i>Comparing differences in the mean</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="scatterplot-and-correlation-coefficient.html"><a href="scatterplot-and-correlation-coefficient.html"><i class="fa fa-check"></i>Scatterplot and Correlation Coefficient</a><ul>
<li class="chapter" data-level="" data-path="scatterplot-and-correlation-coefficient.html"><a href="scatterplot-and-correlation-coefficient.html#the-scatterplot"><i class="fa fa-check"></i>The scatterplot</a></li>
<li class="chapter" data-level="" data-path="scatterplot-and-correlation-coefficient.html"><a href="scatterplot-and-correlation-coefficient.html#the-correlation-coefficient"><i class="fa fa-check"></i>The correlation coefficient</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i>Statistical Inference</a><ul>
<li class="chapter" data-level="" data-path="the-problem-of-statistical-inference.html"><a href="the-problem-of-statistical-inference.html"><i class="fa fa-check"></i>The Problem of Statistical Inference</a></li>
<li class="chapter" data-level="" data-path="the-concept-of-the-sampling-distribution.html"><a href="the-concept-of-the-sampling-distribution.html"><i class="fa fa-check"></i>The Concept of the Sampling Distribution</a><ul>
<li class="chapter" data-level="" data-path="the-concept-of-the-sampling-distribution.html"><a href="the-concept-of-the-sampling-distribution.html#example-class-height"><i class="fa fa-check"></i>Example: class height</a></li>
<li class="chapter" data-level="" data-path="the-concept-of-the-sampling-distribution.html"><a href="the-concept-of-the-sampling-distribution.html#central-limit-theorem-and-the-normal-distribution"><i class="fa fa-check"></i>Central limit theorem and the normal distribution</a></li>
<li class="chapter" data-level="" data-path="the-concept-of-the-sampling-distribution.html"><a href="the-concept-of-the-sampling-distribution.html#what-can-we-do-with-the-sampling-distribution"><i class="fa fa-check"></i>What can we do with the sampling distribution?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i>Confidence Intervals</a><ul>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#what-do-we-mean-by-confident"><i class="fa fa-check"></i>What do we mean by “confident?”</a></li>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#calculating-the-confidence-interval-for-the-sample-mean"><i class="fa fa-check"></i>Calculating the confidence interval for the sample mean</a></li>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#calculating-the-confidence-interval-for-other-sample-statistics"><i class="fa fa-check"></i>Calculating the confidence interval for other sample statistics</a></li>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#example-with-proportions"><i class="fa fa-check"></i>Example with proportions</a></li>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#example-with-mean-differences"><i class="fa fa-check"></i>Example with mean differences</a></li>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#example-with-proportion-differences"><i class="fa fa-check"></i>Example with proportion differences</a></li>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#example-with-correlation-coefficient"><i class="fa fa-check"></i>Example with correlation coefficient</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html"><i class="fa fa-check"></i>Hypothesis Tests</a><ul>
<li class="chapter" data-level="" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#example-coke-winners"><i class="fa fa-check"></i>Example: Coke winners</a></li>
<li class="chapter" data-level="" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#the-general-procedure-of-hypothesis-testing"><i class="fa fa-check"></i>The general procedure of hypothesis testing</a></li>
<li class="chapter" data-level="" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#hypothesis-tests-of-relationships"><i class="fa fa-check"></i>Hypothesis tests of relationships</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="building-models-1.html"><a href="building-models-1.html"><i class="fa fa-check"></i>Building Models</a><ul>
<li class="chapter" data-level="" data-path="the-ols-regression-line.html"><a href="the-ols-regression-line.html"><i class="fa fa-check"></i>The OLS Regression Line</a><ul>
<li class="chapter" data-level="" data-path="the-ols-regression-line.html"><a href="the-ols-regression-line.html#the-formula-for-a-line"><i class="fa fa-check"></i>The Formula for a Line</a></li>
<li class="chapter" data-level="" data-path="the-ols-regression-line.html"><a href="the-ols-regression-line.html#calculating-the-best-fitting-line"><i class="fa fa-check"></i>Calculating the Best-Fitting Line</a></li>
<li><a href="the-ols-regression-line.html#using-the-lm-command-to-calculate-ols-regression-lines-in-r">Using the <code>lm</code> command to calculate OLS regression lines in <em>R</em></a></li>
<li class="chapter" data-level="" data-path="the-ols-regression-line.html"><a href="the-ols-regression-line.html#the-ols-regression-line-as-a-model"><i class="fa fa-check"></i>The OLS regression line as a model</a></li>
<li class="chapter" data-level="" data-path="the-ols-regression-line.html"><a href="the-ols-regression-line.html#interpeting-slopes-and-intercepts"><i class="fa fa-check"></i>Interpeting Slopes and Intercepts</a></li>
<li><a href="the-ols-regression-line.html#how-good-is-x-as-a-predictor-of-y">How good is <span class="math inline">\(x\)</span> as a predictor of <span class="math inline">\(y\)</span>?</a></li>
<li class="chapter" data-level="" data-path="the-ols-regression-line.html"><a href="the-ols-regression-line.html#inference-for-ols-regression-models"><i class="fa fa-check"></i>Inference for OLS Regression models</a></li>
<li class="chapter" data-level="" data-path="the-ols-regression-line.html"><a href="the-ols-regression-line.html#regression-line-cautions"><i class="fa fa-check"></i>Regression Line Cautions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-power-of-controlling-for-other-variables.html"><a href="the-power-of-controlling-for-other-variables.html"><i class="fa fa-check"></i>The Power of Controlling for Other Variables</a><ul>
<li class="chapter" data-level="" data-path="the-power-of-controlling-for-other-variables.html"><a href="the-power-of-controlling-for-other-variables.html#interpreting-results-in-a-multivariate-ols-regression-models"><i class="fa fa-check"></i>Interpreting results in a multivariate OLS regression models</a></li>
<li class="chapter" data-level="" data-path="the-power-of-controlling-for-other-variables.html"><a href="the-power-of-controlling-for-other-variables.html#including-more-than-two-independent-variables"><i class="fa fa-check"></i>Including more than two independent variables</a></li>
<li class="chapter" data-level="" data-path="the-power-of-controlling-for-other-variables.html"><a href="the-power-of-controlling-for-other-variables.html#how-to-read-a-table-of-regression-results"><i class="fa fa-check"></i>How to read a table of regression results</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="including-categorical-variables-as-predictors.html"><a href="including-categorical-variables-as-predictors.html"><i class="fa fa-check"></i>Including Categorical Variables as Predictors</a><ul>
<li class="chapter" data-level="" data-path="including-categorical-variables-as-predictors.html"><a href="including-categorical-variables-as-predictors.html#indicator-variables"><i class="fa fa-check"></i>Indicator variables</a></li>
<li class="chapter" data-level="" data-path="including-categorical-variables-as-predictors.html"><a href="including-categorical-variables-as-predictors.html#categorical-variables-with-more-than-two-categories"><i class="fa fa-check"></i>Categorical variables with more than two categories</a></li>
<li class="chapter" data-level="" data-path="including-categorical-variables-as-predictors.html"><a href="including-categorical-variables-as-predictors.html#categorical-and-quantitative-variables-combined-in-a-single-model"><i class="fa fa-check"></i>Categorical and quantitative variables combined in a single model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="interaction-terms.html"><a href="interaction-terms.html"><i class="fa fa-check"></i>Interaction Terms</a><ul>
<li class="chapter" data-level="" data-path="interaction-terms.html"><a href="interaction-terms.html#the-nature-of-additive-models"><i class="fa fa-check"></i>The nature of additive models</a></li>
<li class="chapter" data-level="" data-path="interaction-terms.html"><a href="interaction-terms.html#the-interaction-term"><i class="fa fa-check"></i>The interaction term</a></li>
<li class="chapter" data-level="" data-path="interaction-terms.html"><a href="interaction-terms.html#interpreting-interaction-terms"><i class="fa fa-check"></i>Interpreting interaction terms</a></li>
<li><a href="interaction-terms.html#interaction-terms-in-r">Interaction terms in <em>R</em></a></li>
<li class="chapter" data-level="" data-path="interaction-terms.html"><a href="interaction-terms.html#interaction-terms-with-multiple-categories"><i class="fa fa-check"></i>Interaction terms with multiple categories</a></li>
<li class="chapter" data-level="" data-path="interaction-terms.html"><a href="interaction-terms.html#interaction-terms-with-two-categorical-variables"><i class="fa fa-check"></i>Interaction terms with two categorical variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="using-scripts.html"><a href="using-scripts.html"><i class="fa fa-check"></i>Using Scripts</a><ul>
<li class="chapter" data-level="" data-path="getting-started-with-scripts.html"><a href="getting-started-with-scripts.html"><i class="fa fa-check"></i>Getting Started with Scripts</a><ul>
<li class="chapter" data-level="" data-path="getting-started-with-scripts.html"><a href="getting-started-with-scripts.html#not-everything-goes-into-your-script"><i class="fa fa-check"></i>Not Everything Goes Into Your Script</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-scripts.html"><a href="getting-started-with-scripts.html#commenting-for-sanity"><i class="fa fa-check"></i>Commenting for Sanity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="object-types.html"><a href="object-types.html"><i class="fa fa-check"></i>Object Types</a><ul>
<li class="chapter" data-level="" data-path="atomic-modes.html"><a href="atomic-modes.html"><i class="fa fa-check"></i>Atomic Modes</a></li>
<li class="chapter" data-level="" data-path="vectors-and-matrices.html"><a href="vectors-and-matrices.html"><i class="fa fa-check"></i>Vectors and Matrices</a><ul>
<li class="chapter" data-level="" data-path="vectors-and-matrices.html"><a href="vectors-and-matrices.html#vectors"><i class="fa fa-check"></i>Vectors</a></li>
<li class="chapter" data-level="" data-path="vectors-and-matrices.html"><a href="vectors-and-matrices.html#matrices"><i class="fa fa-check"></i>Matrices</a></li>
<li class="chapter" data-level="" data-path="vectors-and-matrices.html"><a href="vectors-and-matrices.html#indexing-vectors-and-matrices"><i class="fa fa-check"></i>Indexing Vectors and Matrices</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="factors.html"><a href="factors.html"><i class="fa fa-check"></i>Factors</a><ul>
<li class="chapter" data-level="" data-path="factors.html"><a href="factors.html#re-ordering-categories-in-factors"><i class="fa fa-check"></i>Re-ordering categories in factors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logical-values-and-boolean-statements.html"><a href="logical-values-and-boolean-statements.html"><i class="fa fa-check"></i>Logical Values and Boolean Statements</a></li>
<li class="chapter" data-level="" data-path="missing-values.html"><a href="missing-values.html"><i class="fa fa-check"></i>Missing Values</a></li>
<li class="chapter" data-level="" data-path="lists.html"><a href="lists.html"><i class="fa fa-check"></i>Lists</a><ul>
<li class="chapter" data-level="" data-path="lists.html"><a href="lists.html#accessing-elements-of-the-list"><i class="fa fa-check"></i>Accessing elements of the list</a></li>
<li><a href="lists.html#the-lapply-command-is-awesome">The <code>lapply</code> command is awesome</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-frames.html"><a href="data-frames.html"><i class="fa fa-check"></i>Data Frames</a><ul>
<li><a href="data-frames.html#renaming-variables-in-a-data.frame">Renaming Variables in a <code>data.frame</code></a></li>
<li class="chapter" data-level="" data-path="data-frames.html"><a href="data-frames.html#subsetting-data-frames"><i class="fa fa-check"></i>Subsetting Data Frames</a></li>
<li class="chapter" data-level="" data-path="data-frames.html"><a href="data-frames.html#subsetting-by-variables"><i class="fa fa-check"></i>Subsetting by variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="pretty-pictures.html"><a href="pretty-pictures.html"><i class="fa fa-check"></i>Pretty Pictures</a><ul>
<li class="chapter" data-level="" data-path="base-plot.html"><a href="base-plot.html"><i class="fa fa-check"></i>Base Plot</a></li>
<li class="chapter" data-level="" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i>ggplot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reading-and-writing-data.html"><a href="reading-and-writing-data.html"><i class="fa fa-check"></i>Reading and Writing Data</a><ul>
<li class="chapter" data-level="" data-path="data-formats.html"><a href="data-formats.html"><i class="fa fa-check"></i>Data Formats</a></li>
<li class="chapter" data-level="" data-path="plain-text-files.html"><a href="plain-text-files.html"><i class="fa fa-check"></i>plain text files</a><ul>
<li class="chapter" data-level="" data-path="plain-text-files.html"><a href="plain-text-files.html#working-with-csv-files"><i class="fa fa-check"></i>Working with CSV files</a></li>
<li class="chapter" data-level="" data-path="plain-text-files.html"><a href="plain-text-files.html#working-with-fixed-width-text-files"><i class="fa fa-check"></i>Working with fixed-width text files</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-in-binary-format.html"><a href="data-in-binary-format.html"><i class="fa fa-check"></i>Data in binary format</a></li>
<li class="chapter" data-level="" data-path="saving-data.html"><a href="saving-data.html"><i class="fa fa-check"></i>Saving data</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Analysis in Sociology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="confidence-intervals" class="section level2">
<h2>Confidence Intervals</h2>
<p>Remember from the previous section that 95% of all the possible sample means will be within 1.96 standard errors of the true population mean <span class="math inline">\(\mu\)</span>. Therefore:</p>
<p><img src="stat_book_files/figure-html/normaldist_ci-1.png" width="500px" height="400px" /></p>
<p>There is a 95% probability that we will draw a sample mean within 1.96 standard errors of the true population mean.</p>
<p>Lets say I were to construct the following interval for every possible sample:</p>
<p><span class="math display">\[\bar{x}\pm1.96(\sigma/\sqrt{n})\]</span></p>
<p>t follows from the probability statement above that for 95% of all samples, this interval would contain the true population mean, <span class="math inline">\(\mu\)</span>.</p>
<p>To see how this works graphically, imagine constructing this interval for twenty different samples from the same population.</p>
<p><img src="stat_book_files/figure-html/conf_intervals-1.png" width="500px" height="400px" /></p>
<p>The blue line gives the true population mean. The dots represent the sample means for each of the twenty samples. You can see that these sample means fluctuate around the true population mean due to random sampling error. The lines give the interval outlined above. In 19 out of the 20 cases, this interval contains the true population mean (as you can see by the fact that the interval crosses the blue line). The one sample where this is not true is shown in red. On average, 95% of samples will contain the true population mean in the interval, so 5% or 1 in 20 will not.</p>
<p>We refer to this interval as the <strong>95% confidence interval</strong>. Of course, in practice, we only construct one interval on the sample that we have. We use this interval to give a range of values that we feel “confident” will contain the true population mean.</p>
<div id="what-do-we-mean-by-confident" class="section level3">
<h3>What do we mean by “confident?”</h3>
<p>The term “confident” is a little ambiguous. Given my statements above, it might be tempting to interpret the 95% confidence interval to mean that there is a 95% probability that the true population mean is within the interval. This interpretation seems intuitive and straightforward, but that interpretation is incorrect according to the classic approach to inference. The problem here is subtle, but from the classical viewpoint, probability is an <strong>objective</strong> phenomenon that relates to the outcomes of future processes over the long run. From this viewpoint, we cannot express our <strong>subjective</strong> uncertainties about numbers in terms of probabilities.The population mean is a single static number. This leads us to a sort of <a href="https://www.youtube.com/watch?v=BQ4yd2W50No">yoda-like</a> statement: The population mean is either in your interval or it is not. There is no probability.</p>
<p>This is why we use a more neutral term like “confidence.” If we want to be long-winded about it, we might say that we are 95% confident because “in 95% of all the possible samples I could have drawn, the true population mean would be in the interval. I don’t know if I have one of those 95% or the unlucky 5%, but nonetheless, there it is.”</p>
<p>If this all seems a bit confusing, you are perfectly normal. As I said, this is the classic view of probability. Intuitively, people often think of uncertainty in probabilistic terms (e.g. what are the odds your team will win the game?). Many contemporary statisticians would in fact agree that it is perfectly okay to express subjective uncertainty as a probability. But, I still need to let you know that from the classic approach, interpreting your confidence interval as a probability statement is a no-no.</p>
</div>
<div id="calculating-the-confidence-interval-for-the-sample-mean" class="section level3">
<h3>Calculating the confidence interval for the sample mean</h3>
<p>Okay, lets try calculating a confidence interval. Lets try this out for age in the politics dataset. The formula is:</p>
<p><span class="math display">\[\bar{x}\pm1.96(\sigma/\sqrt{n})\]</span></p>
<p>Oh wait, we can’t do it! We don’t know the value of the population standard deviation <span class="math inline">\(\sigma\)</span>. As I explained in the last section, we are going to have to do a little “fudging” here. Instead of <span class="math inline">\(\sigma\)</span>, we can use our sample standard deviation <span class="math inline">\(s\)</span>. However, doing so will have consequences. Here is our new formula:</p>
<p><span class="math display">\[\bar{x} \pm t*(s\sqrt{n})\]</span></p>
<p>As you can see, I have replaced the 1.96 with some number <span class="math inline">\(t\)</span>, referred to as the <strong>t-statistic</strong>. Basically to adjust for the greater uncertainty in using a sample statistic in my calculation of the standard error, I need to increase the number here slightly from 1.96. How much I increase it will depend on the <strong>degrees of freedom</strong> which are given by the sample size minus one (<span class="math inline">\(n-1\)</span>). To figure out the correct t-statistic, I can use the <code>qt</code> command in <em>R</em>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="kw">nrow</span>(politics)<span class="op">-</span><span class="dv">1</span>)</code></pre>
<pre><code>## [1] 1.960524</code></pre>
<p>The first command to <code>qt</code> is the confidence you want. This is a little bit tricky because for a 95% confidence interval, we actually want to input 0.975. This is because we are basically asking for only the upper tail of that normal distribution shown at the beginning of this section. This area contains only 2.5% of the area outside, with the other 2.5% being in the lower tail. The second number is the degrees of freedom which equals <span class="math inline">\(n-1\)</span>. In this case, we have such a large sample, that the t-statistic we need is very close to 1.96.</p>
<p>In smaller samples, using the t-statistic rather than 1.96 can make a bigger difference. Its not a proper sample, but lets take the case of the crime data. Here there are only 51 observations, so the t-statistic is:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dv">51-1</span>)</code></pre>
<pre><code>## [1] 2.008559</code></pre>
<p>The difference from 1.96 is a little more noticeable.</p>
<p>Lets return to the politics data. We now have all the information we need to calculate the 95% confidence interval:</p>
<pre class="sourceCode r"><code class="sourceCode r">xbar &lt;-<span class="st"> </span><span class="kw">mean</span>(politics<span class="op">$</span>age)
sdx &lt;-<span class="st"> </span><span class="kw">sd</span>(politics<span class="op">$</span>age)
n &lt;-<span class="st"> </span><span class="kw">nrow</span>(politics)
se &lt;-<span class="st"> </span>sdx<span class="op">/</span><span class="kw">sqrt</span>(n)
t &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>,n<span class="dv">-1</span>)
xbar<span class="op">+</span>t<span class="op">*</span>se</code></pre>
<pre><code>## [1] 50.03165</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">xbar<span class="op">-</span>t<span class="op">*</span>se</code></pre>
<pre><code>## [1] 48.97307</code></pre>
<p>We are 95% confident that the mean age among all US adults is between 49.01 and 49.87 years of age. As you can see, the large sample of nearly 6,000 respondents produces a very tight confidence interval.</p>
</div>
<div id="calculating-the-confidence-interval-for-other-sample-statistics" class="section level3">
<h3>Calculating the confidence interval for other sample statistics</h3>
<p>As noted in the previous section, the sampling distribution of other sample statistics such as proportions, mean differences, and regression slopes is also normally distributed in large enough samples. This means that we can use the same approach to construct confidence intervals for other sample statistics. The general form of the confidence interval is:</p>
<p><span class="math display">\[(sample statistic) \pm t*(standard error)\]</span></p>
<p>In order to do this for any of the above sample statistics, we only need to know how to calculate that sample statistic’s standard error and the degrees of freedom used to look up the t-statistic for that sample statistic. Here is a useful cheat sheet of those formulas:</p>
<table>
<thead>
<tr class="header">
<th align="left">Type</th>
<th align="left">SE</th>
<th>df for <span class="math inline">\(t\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Mean</td>
<td align="left"><span class="math inline">\(s/\sqrt{n}\)</span></td>
<td><span class="math inline">\(n-1\)</span></td>
</tr>
<tr class="even">
<td align="left">Proportion</td>
<td align="left"><span class="math inline">\(\sqrt\frac{\hat{p}*(1-\hat{p})}{n}\)</span></td>
<td><span class="math inline">\(n-1\)</span></td>
</tr>
<tr class="odd">
<td align="left">Mean Difference</td>
<td align="left"><span class="math inline">\(\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}\)</span></td>
<td>min(<span class="math inline">\(n_1-1\)</span>,<span class="math inline">\(n_2-1\)</span>)</td>
</tr>
<tr class="even">
<td align="left">Proportion Difference</td>
<td align="left"><span class="math inline">\(\sqrt{\frac{\hat{p}_1*(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2*(1-\hat{p}_2)}{n_2}}\)</span></td>
<td>min(<span class="math inline">\(n_1-1\)</span>,<span class="math inline">\(n_2-1\)</span>)</td>
</tr>
<tr class="odd">
<td align="left">Correlation Coefficient</td>
<td align="left"><span class="math inline">\(\sqrt{\frac{1-r^2}{n-2}}\)</span></td>
<td><span class="math inline">\(n-2\)</span></td>
</tr>
</tbody>
</table>
<p>I know some of that math might look intimidating but I will go through an example of each case below to show you how it works for each case.</p>
</div>
<div id="example-with-proportions" class="section level3">
<h3>Example with proportions</h3>
<p>As an example, lets use the proportion of respondents who do not believe in anthropogenic climate change. In our politics sample, we get:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(politics<span class="op">$</span>globalwarm)</code></pre>
<pre><code>## 
##   No  Yes 
## 1180 3058</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">1181</span><span class="op">+</span><span class="dv">3057</span>
p_hat &lt;-<span class="st"> </span><span class="dv">1181</span><span class="op">/</span>n
n</code></pre>
<pre><code>## [1] 4238</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">p_hat</code></pre>
<pre><code>## [1] 0.2786692</code></pre>
<p>About 27.9% of the respondents in our sample are climate change deniers. What can we conclude about the proportion in the US population? First, lets figure out the t-statistic. We use the same <span class="math inline">\(n-1\)</span> for degrees of freedom:</p>
<pre class="sourceCode r"><code class="sourceCode r">t_stat &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, n<span class="dv">-1</span>)
t_stat</code></pre>
<pre><code>## [1] 1.960524</code></pre>
<p>Our sample is large enough that we are basically using 1.96. Now we need to calculate the standard error. The formula from above is:</p>
<p><span class="math display">\[\sqrt{\frac{\hat{p}*(1-\hat{p})}{n}}\]</span></p>
<p>The term <span class="math inline">\(hat{p}\)</span> is the standard way to represent the sample proportion, which in this case is 0.279. So, our formula is:</p>
<p><span class="math display">\[\sqrt{\frac{0.279*(1-0.279)}{4238}}\]</span></p>
<p>We can calculate this in <em>R</em>:</p>
<pre class="sourceCode r"><code class="sourceCode r">se &lt;-<span class="st"> </span><span class="kw">sqrt</span>(p_hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_hat)<span class="op">/</span>n)
se</code></pre>
<pre><code>## [1] 0.006887018</code></pre>
<p>We now have all the pieces to construct the confidence interval:</p>
<pre class="sourceCode r"><code class="sourceCode r">p_hat<span class="op">+</span>t_stat<span class="op">*</span>se</code></pre>
<pre><code>## [1] 0.2921713</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">p_hat<span class="op">-</span>t_stat<span class="op">*</span>se</code></pre>
<pre><code>## [1] 0.265167</code></pre>
<p>We are 95% confident that the true percentage of climate change deniers in the the US population is between 26.5% and 29.2%.</p>
</div>
<div id="example-with-mean-differences" class="section level3">
<h3>Example with mean differences</h3>
<p>using our Add health data, what is the mean difference in popularity (number of friend nominations) between frequent smokers and those who do not smoke frequently?</p>
<pre class="sourceCode r"><code class="sourceCode r">tab &lt;-<span class="st"> </span><span class="kw">tapply</span>(addhealth<span class="op">$</span>indegree, addhealth<span class="op">$</span>smoker, mean)
tab</code></pre>
<pre><code>## Non-smoker     Smoker 
##   4.509636   4.782148</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">mean_diff &lt;-<span class="st"> </span><span class="fl">4.782148</span> <span class="op">-</span><span class="st"> </span><span class="fl">4.509636</span>
mean_diff</code></pre>
<pre><code>## [1] 0.272512</code></pre>
<p>In our sample data, frequent smokers had 0.273 more friends on average than those who did not smoke frequently. What is the confidence interval for that value in the population? We start by calculating the t-statitic for this confidence interval. We use the size of the smaller group minus one for the degrees of freedom.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(addhealth<span class="op">$</span>smoker)</code></pre>
<pre><code>## 
## Non-smoker     Smoker 
##       3736        661</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">n1 &lt;-<span class="st"> </span><span class="dv">3736</span>
n2 &lt;-<span class="st"> </span><span class="dv">661</span>
t_stat &lt;-<span class="st"> </span><span class="kw">qt</span>(.<span class="dv">975</span>, n2<span class="dv">-1</span>)
t_stat</code></pre>
<pre><code>## [1] 1.963565</code></pre>
<p>The value is pretty close to 1.96 but a little bigger. Now we need to calculate the standard error. The formula is:</p>
<p><span class="math display">\[\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}\]</span>
We already have <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span>, so we just need to get the standard deviation of friend nominations for the two groups to get <span class="math inline">\(s_1\)</span> and <span class="math inline">\(s_2\)</span>. We can do this with another tapply command, but changing from <code>mean</code> to <code>sd</code> in the third argument.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(addhealth<span class="op">$</span>indegree, addhealth<span class="op">$</span>smoker, sd)</code></pre>
<pre><code>## Non-smoker     Smoker 
##   3.658650   3.869584</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">s1 &lt;-<span class="st"> </span><span class="fl">3.65865</span>
s2 &lt;-<span class="st"> </span><span class="fl">3.869584</span>
se &lt;-<span class="st"> </span><span class="kw">sqrt</span>(s1<span class="op">^</span><span class="dv">2</span><span class="op">/</span>n1<span class="op">+</span>s2<span class="op">^</span><span class="dv">2</span><span class="op">/</span>n2)
se</code></pre>
<pre><code>## [1] 0.1619752</code></pre>
<p>Now we have all the pieces to put together the confidence interval:</p>
<pre class="sourceCode r"><code class="sourceCode r">mean_diff <span class="op">-</span><span class="st"> </span>t_stat<span class="op">*</span>se</code></pre>
<pre><code>## [1] -0.04553685</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">mean_diff <span class="op">+</span><span class="st"> </span>t_stat<span class="op">*</span>se</code></pre>
<pre><code>## [1] 0.5905609</code></pre>
<p>We are 95% confident that in the population of US adolescents, those who smoke frequently have between 0.05 fewer to 0.59 more friend nominations, on average, than those who do not smoke frequently. Note that because our confidence interval contains both negative and positive value, we cannot be confident about whether smoking is truly associated with having more or less friends. The direction of the relationship between the two variables is uncertain.</p>
</div>
<div id="example-with-proportion-differences" class="section level3">
<h3>Example with proportion differences</h3>
<p>Lets continue to use the Add Health data. Do we observe a gender difference in smoking behavior in our sample?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.table</span>(<span class="kw">table</span>(addhealth<span class="op">$</span>smoker, addhealth<span class="op">$</span>sex), <span class="dv">2</span>)</code></pre>
<pre><code>##             
##                 Female      Male
##   Non-smoker 0.8543563 0.8444976
##   Smoker     0.1456437 0.1555024</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">p_hat_f &lt;-<span class="st"> </span><span class="fl">0.1456</span>
p_hat_m &lt;-<span class="st"> </span><span class="fl">0.1555</span>
p_hat_diff &lt;-<span class="st"> </span>p_hat_m<span class="op">-</span>p_hat_f
p_hat_diff</code></pre>
<pre><code>## [1] 0.0099</code></pre>
<p>In our sample, about 14.6% of girls were frequent smokers and about 15.6% of boys were frequent smokers. The percentage of boys who smoke is about 1% higher than the percentage of girls. Do we think this moderate difference in the sample is true in the population?</p>
<p>Lets start again by calculating the appropriate t-statistic for our confidence interval. We use the same procedure as for mean differences above, choosing the size of the smaller group for the degrees of freedom. However, its important to note that our groups are now boys and girls, not smokers and non-smokers.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(addhealth<span class="op">$</span>sex)</code></pre>
<pre><code>## 
##  Female    Male 
##    2307    2090</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">n_f &lt;-<span class="st"> </span><span class="dv">2307</span>
n_m &lt;-<span class="st"> </span><span class="dv">2090</span>
t_stat &lt;-<span class="st"> </span><span class="kw">qt</span>(.<span class="dv">975</span>, n_m<span class="dv">-1</span>)
t_stat</code></pre>
<pre><code>## [1] 1.9611</code></pre>
<p>Now we can calculate the standard error. The formula is:</p>
<p><span class="math display">\[\sqrt{\frac{\hat{p}_1*(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2*(1-\hat{p}_2)}{n_2}}\]</span></p>
<p>That looks like a lot, but we just have to focus on pluggin in the right values in R:</p>
<pre class="sourceCode r"><code class="sourceCode r">se &lt;-<span class="st"> </span><span class="kw">sqrt</span>((p_hat_f<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_hat_f)<span class="op">/</span>n_f)<span class="op">+</span>(p_hat_m<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_hat_m)<span class="op">/</span>n_m))
se</code></pre>
<pre><code>## [1] 0.01080535</code></pre>
<p>Now we have all the parts to calculate the confidence interval:</p>
<pre class="sourceCode r"><code class="sourceCode r">p_hat_diff <span class="op">-</span><span class="st"> </span>t_stat<span class="op">*</span>se</code></pre>
<pre><code>## [1] -0.01129037</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">p_hat_diff <span class="op">+</span><span class="st"> </span>t_stat<span class="op">*</span>se</code></pre>
<pre><code>## [1] 0.03109037</code></pre>
<p>We are 95% confident that in the population of US adolescents, between 1.1% fewer to 3.1% more boys smoke frequently than girls. As above, because our confidence interval includes both negative and positive values, we are not very confident at all about whether boys or girls smoke more frequently.</p>
</div>
<div id="example-with-correlation-coefficient" class="section level3">
<h3>Example with correlation coefficient</h3>
<p>Lets stick with the Add Health data. What is the correlation between GPA and the number of friend nominations that a student receives?</p>
<pre class="sourceCode r"><code class="sourceCode r">r &lt;-<span class="st"> </span><span class="kw">cor</span>(addhealth<span class="op">$</span>pseudoGPA, addhealth<span class="op">$</span>indegree)
r</code></pre>
<pre><code>## [1] 0.1685929</code></pre>
<p>In our sample, there is a moderately positive correlation between a student’s GPA and the number of friend nominations that a student receives. What is our confidence interval for the population?</p>
<p>For the t-statistic, we use <span class="math inline">\(n-2\)</span> for the degrees of freedom:</p>
<pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="kw">nrow</span>(addhealth)
t_stat &lt;-<span class="st"> </span><span class="kw">qt</span>(.<span class="dv">975</span>, n<span class="dv">-2</span>)</code></pre>
<p>For the standard error, the formula is:</p>
<p><span class="math display">\[\sqrt{\frac{1-r^2}{n-2}}\]</span>
This is straightforward to calculate in R:</p>
<pre class="sourceCode r"><code class="sourceCode r">se &lt;-<span class="st"> </span><span class="kw">sqrt</span>((<span class="dv">1</span><span class="op">-</span>r<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span>(n<span class="dv">-2</span>))
se</code></pre>
<pre><code>## [1] 0.01486822</code></pre>
<p>Now we have all the parts we need to calculate the confidence interval:</p>
<pre class="sourceCode r"><code class="sourceCode r">r <span class="op">-</span><span class="st"> </span>t_stat<span class="op">*</span>se</code></pre>
<pre><code>## [1] 0.1394437</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">r <span class="op">+</span><span class="st"> </span>t_stat<span class="op">*</span>se</code></pre>
<pre><code>## [1] 0.1977421</code></pre>
<p>We are 95% confident that the true correlation coefficient between GPA and friend nominations in the population of US adolescents is between 0.139 and 0.198. While there is some difference in the strength of that relationship, we are pretty confident that the correlation is moderatly positive.</p>
<hr />
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="the-concept-of-the-sampling-distribution.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="hypothesis-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
